name: 'Wolf Bites Tweets'
description: 'Using twitter api to get tweets a user liked or tweeted and save as json files.'

branding:
  icon: 'chevrons-down'
  color: 'purple'

inputs:
  screen-name:
    description: 'The screen name of the twitter account.'
    required: true
  bearer-token:
    description: 'The bearer token from your twitter dev account.'
    required: true
  get-type:
    description: 'What kind of data you want to get.[tweets, likes, both]'
    default: 'tweets'
    required: false
  count:
    description: 'How many tweets you want to get.'
    default: '10,10'
    required: false
  if-only-media:
    description: 'Do you want your result only contain tweets that contain media.'
    default: false
    required: false
  output-dir:
    description: 'The directory name that the json file will store'
    default: 'output'
    required: false

runs:
  using: node12
  main: index.js